### ISSUE TITLE
请问是否有轻声读音？

### ISSUE THREAD

**Issue by shiyanpei0826** [mapull/chinese-dictionary#13]
请问读音体系里是否有轻声的读音？

**Comment by mapull** [comment]
汉字中的轻声读音举例：

`{

    "index" : 1915,
    "char" : "啊",
    "strokes" : 10,
    "pinyin" : [
        "ā",
        "á",
        "ǎ",
        "à",
        "a"
    ],
    "radicals" : "口",
    "frequency" : 1,
    "structure" : "H2"
}`

包含轻声的词语

`{
    "word" : "班子",
    "pinyin" : "bān zi",
    "abbr" : "bz",
    "explanation" : "剧团的旧称； 泛指为执行一定任务而成立的组织领导～ㄧ生产～。"
}
`

包含轻声的成语

`{
    "word" : "一就手儿",
    "pinyin" : "yī jiù shǒu er",
    "abbr" : "yjse",
    "explanation" : "一就：顺便。指趁做某事之时捎带着做另一件事。",
    "source" : {
        "text" : "索性劳你的驾，连灰带麻刀，一就手儿给买了来。",
        "book" : "清·文康《儿女英雄传》第三十二回"
    }
}
`
