### ISSUE TITLE
成语库中，拼音分隔符混乱

### ISSUE THREAD

**Issue by caiyouzai** [mapull/chinese-dictionary#3]
有用双空格分割的，有用单空格的，有用 \u3000 分割的，有用\xa0分格的，格式混乱，还有成语拼音是中文的，ex："word" : "布衣韦带", "pinyin" : "布衣韦带", "abbr" : "bywd"

**Comment by caiyouzai** [comment]
同样的问题还出现在了
{'word': '悬龟系鱼', 'pinyin': 'xuán  guī\ue4c6jì  yú'}
{'word': '懵里懵懂', 'pinyin': 'měng  měng  dǒng'}
{'word': '改行自新', 'pinyin': 'gǎi  xíng  zìxīn'}
{'word': '足尺加二', 'pinyin': 'zú  chǐ  ji?èr'}
{'word': '跌宕风流', 'pinyin': 'diē  dàng  fēngliú'}

**Comment by mapull** [comment]
目前一直在校准汉字部分的数据。词语的校准预计下个月开始。词语的数据比较庞大，校准会花比较多时间。
感谢关注，我们会优先处理上述拼音问题。

**Comment by mapull** [comment]
上述问题已经修复。
