### ISSUE TITLE
related.json未上传

### ISSUE THREAD

**Issue by AnShengqiang** [mapull/chinese-dictionary#4]
您好，readme中提到的related.json在项目中没有找到。

<img width="857" alt="image" src="https://user-images.githubusercontent.com/12854979/180716093-6dad0c3b-64d1-4399-93b1-4fa27bd06691.png">

请问这个json文件方便上传吗？

**Comment by mapull** [comment]
内容还在整理中，整理完成后上传

**Comment by mapull** [comment]
数据已上传
