### ISSUE TITLE
请问一下word.json那些词语的解释，是来源自哪里呢？

### ISSUE THREAD

**Issue by another1s** [mapull/chinese-dictionary#7]
您好！非常感谢您的开源！我有一个小问题，我看到里面含有大量的古词语（或者说并不是很常见的词语），这些是全部来自于词典吗？我斗胆猜测，现在网上的公开语料数据大概很少看到这些词汇

**Comment by mapull** [comment]
数据来源非常多，Github 上排名前几的中文词库，都有做参考，还有其他一些开源的数据库也进行了一些数据整理。还找了一些商业的数据作为补充和数据订正。
